apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mariadb-daemonset
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb-container
          image: mariadb:latest
          ports:
            - containerPort: 8080
