apiVersion: v1
kind: Namespace
metadata:
  name: db-replicaset
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: db-replicaset
  name: mariadb-replicaset
  labels:
    app: mariadb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "256Mi"
            cpu: "128m"
          requests:
            memory: "128Mi"
            cpu: "64m"
