apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mariadb-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb-container
          image: mariadb:latest
          ports:
            - containerPort: 8080
