apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rox
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data-rox"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rox
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-rox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rox
  template:
    metadata:
      labels:
        app: nginx-rox
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: "/usr/share/nginx/html" 
              name: volume-rox
              readOnly: true 
      volumes:
        - name: volume-rox
          persistentVolumeClaim:
            claimName: pvc-rox